301/lesson4/lecture8/postit/config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  
  resources :categories, only: [:new, :create, :show]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/register', to: "users#new"
  resources :users, only: [:show, :create, :edit, :update]
end

301/lesson4/lecture8/postit/app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  belongs_to :post

  validates :body, presence: true
end

301/lesson4/lecture8/postit/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :require_user

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(vote: params[:vote], creator: current_user, voteable: @comment)

    respond_to do |format|
      format.js
    end
  end

  def create
    @comment = @post.comments.build(params.require(:comment).permit(:body))

    #obj to obj, id to id
    #virtual attr creator to current_user obj
    @comment.creator = current_user

    if @comment.save
      flash[:notice] = "Saved comment"
      redirect_to post_path(@post)
    else
      flash[:error] = @comment.errors.full_messages
      redirect_to post_path(@post)
    end
  end

  private
  def set_post
    @post = Post.find_by(slug: params[:post_id])
  end
end

301/lesson4/lecture8/postit/app/views/comments/_comment.html.erb
<% show_post ||= false %>

<div class="row">
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
      <br>
    <% end %>
    <span id="comment_votes_<%= comment.id %>"><%= comment.total_votes %></span> Votes
    <% if logged_in? %>
      <br>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>
  <div class="span4 well">
    <% if show_post %>
      <p>on <em><%= link_to comment.post.title, post_path(comment.post) %></em></p>
    <% end %>
    <em><%= comment.body %></em>
    <p>
      <span class="quiet">posted by <%= link_to(comment.creator.username, user_path(comment.creator)) %></span>
      <small>at <%= comment.created_at %></small>
    </p>
  </div>
</div>

301/lesson4/lecture8/postit/app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $('span#comment_votes_<%= @comment.id %>').text('<%= @comment.total_votes %>')
<% else %>
  <% flash[:error] = 'something wrong' %>
  window.location.reload();
<% end %>