301/lesson4/todos/config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'todos#index'

  resources :todos do
    member do
      post :completed
    end
  end

  
  resources :users, only: [:show, :edit, :update] do
    member do
      post :clear, as: 'clear_todos'
    end
  end

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

301/lesson4/todos/app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user

  default_scope order('completed_at ASC')

  validates :title, presence: true, length: { minimum: 3, maximum: 20 }
  validates :description, presence: true, length: { minimum: 5, maximum: 100 }
  validates :completed_at, presence: true
end

301/lesson4/todos/app/models/user.rb
class User < ActiveRecord::Base
  has_many :todos

  validates :username, presence: true, uniqueness: true, length: {minimum: 3, maximum: 20}
  validates :password, presence: true, length: {minimum: 3, maximum: 20}
  
  has_secure_password validations: false
end

301/lesson4/todos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:notice] = "Please login or register"
      redirect_to login_path
    end
  end

  def same_user
    if (logged_in?)
      if params[:id].blank? || (params[:id] != current_user.id.to_s)
        flash[:notice] = "Cannot access!"
        redirect_to root_path
      end
    end
  end
end

301/lesson4/todos/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :same_user, except: [:destroy]

  def create
    @user = User.find_by(username: params[:username])

    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}!"
      redirect_to user_path(current_user)
    else
      flash[:notice] = "Wrong username or password!"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

301/lesson4/todos/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :get_todo, only: [:edit, :update, :destroy, :completed]
  before_action :require_user, except: [:index]
  def index
    @todos = Todo.all.order('created_at DESC')
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    current_user.todos << @todo
    
    if @todo.save
      flash[:notice] = "Successfully added #{@todo.title}."
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def update
    if @todo.update(todo_params)
      flash[:notice] = "Successfully update #{@todo.title}."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    Todo.destroy(@todo)

    @notice = "Successfully delete #{@todo.title}."

    respond_to do |format|
      format.html do
        flash[:notice] = @notice
        redirect_to user_path(current_user)
      end

      format.js
    end
  end

  def completed
    @todo.update(completed: !@todo.completed)

    respond_to do |format|
      format.html do
        redirect_to user_path(current_user)
      end
      
      format.js
    end
  end

  private
  def todo_params
    params.require(:todo).permit(:title, :description, :completed_at)
  end

  def get_todo
    @todo = Todo.find(params[:id])

    if @todo.user != current_user
      redirect_to user_path(current_user)
    end
  end
end

301/lesson4/todos/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]
  before_action :same_user

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Hi #{@user.username}!"
      redirect_to user
    else
      render :new
    end
  end

  def show
    @user = User.find(current_user)
    @todos = @user.todos
    
    if params["completed"]
      completed = true if params["completed"] == "true"
      completed = false if params["completed"] == "false"
      @todos = @todos.where(completed: completed)
    end
  end

  def clear
    @user = User.find(current_user)
    todo = @user.todos.where(completed: true)
    
    Todo.delete(todo)
    @notice = "Clear completed todos!"
    
    respond_to do |format|
      format.html do
        flash[:notice] = @notice
        redirect_to user_path(current_user)
      end

      format.js
    end
    
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

301/lesson4/todos/app/helpers/application_helper.rb
module ApplicationHelper
  def shorten(string, limit=7)
    string.size > limit ? string[0..limit] + '...' : string
  end
end

301/lesson4/todos/app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      = content_tag :div, msg, :id => "flash_#{name}"

301/lesson4/todos/app/views/layouts/_navigation.html.haml
%nav.user
  - if logged_in?
    = link_to user_path(current_user), method: "get" do
      %i.fa.fa-user
      = current_user.username
    %span | |
    = link_to logout_path, method: "delete" do
      %i.fa.fa-sign-out
      Logout
  - else
    = link_to login_path do
      %i.fa.fa-sign-in
      Login
    %span | |
    = link_to register_path do
      %i.fa.fa-registered
      Register

301/lesson4/todos/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title Todos
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)  
  %body
    = render "/layouts/navigation"
    = render "/layouts/messages"
    = yield

301/lesson4/todos/app/views/shared/_errors.html.haml
- if errors.size > 0
  .alert-error
    - errors.each do |error|
      %p - #{error}

301/lesson4/todos/app/views/todos/_form.html.haml
= render "/shared/errors", errors: @todo.errors.full_messages

%main
  %h1 Todos
  = form_for @todo do |f|
    %fieldset
      = f.text_field :title, placeholder: "What needs to be done?"
      = f.date_field :completed_at, 'data-date'=> @todo.completed_at
      = f.text_area :description, placeholder: "Additional information."
      = f.submit @todo.new_record? ? "Create" : "Update", class: "button"
      %button= link_to "Cancel", user_path(current_user), method: "get"

:javascript
  $(function(){
    var date = $('input[type="date"]');
    date.on('change', function(e) {
      $(this).css('color', 'black')
    });
    date.val(`#{@todo.completed_at}`);
    if (!!date.val()) {
      date.css('color', 'black');
    }
  });

301/lesson4/todos/app/views/todos/completed.js.erb
$('#todos').find('li[data-id=<%= @todo.id %>]').toggleClass('complete')

301/lesson4/todos/app/views/todos/destroy.js.erb
var $alert = $('<div />', {"class": "alert alert-success", "text": `<%= @notice %>`});
$('#todos').find('li[data-id=<%= @todo.id %>]').remove();
$alert.prependTo($('body')).fadeOut(3000);

301/lesson4/todos/app/views/todos/edit.html.haml
= render "form"

301/lesson4/todos/app/views/todos/index.html.haml
%main
  %h1 Todos
  %table

    - @todos.each do |todo|
      %tr
        %td= "\"#{shorten(todo.title)}\""
        %td= "#{time_ago_in_words(todo.created_at)} ago"
        %td= "by #{todo.user.username}"

301/lesson4/todos/app/views/todos/new.html.haml
%main
  %h1 Todos
  = form_for @todo, method: "post" do |f|
    %fieldset
      = f.text_field :title, placeholder: "What needs to be done?"
      -# = f.date_field :date
      -# = date_field("date", "time", {required: true})
      = f.text_area :description, placeholder: "Additional information."
      = f.submit "Submit", class: "button"
      %button= link_to "Cancel", root_path