301/lesson4/lecture8/postit/config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  
  resources :categories, only: [:new, :create, :show]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/register', to: "users#new"
  resources :users, only: [:show, :create, :edit, :update]
end

301/lesson4/lecture8/postit/app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable

  #set creator virtual attributes from User class to Post model
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  
  validates :title, :url, :description, presence: true

  after_validation :generate_slug

  def generate_slug
    self.slug = self.title.gsub(/\W/, '-').downcase
  end

  def to_param
    self.slug
  end
end

301/lesson4/lecture8/postit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:vote, :show, :edit, :update]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]

  def vote
    @vote = Vote.create(vote: params[:vote], creator: current_user, voteable: @post)

    respond_to do |format|
      format.js
    end
  end

  def index
    @posts = Post.all.sort_by{|x| x.votes.size}.reverse
  end

  def show
    @comment = Comment.new
  end

  def new
    #if errors occurs when posted from create action
    #flash[:error] is equal to errors arrays which contains errors messages from action#create
    @post = Post.new
    @comment = Comment.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user

    if @post.save
      flash[:success] = "Post created!"
      redirect_to posts_path
    else
      #flash is rails way to pass primitive(String, array, hash) between action
      #assign flash[:error] to @post.errors.full_messages which contains errors array when POST
      flash[:error] = @post.errors.full_messages
      #Redirect back to form
      redirect_to new_post_path
    end
  end

  def edit; end

  def update
    #set @post to model with params[:id]
    # @post = Post.find(params[:id])

    #call update to update @post with updated attributes from the form; post_params
    #return true if success
    if @post.update(post_params)
      flash[:success] = "Post #{@post.id} updated!"
      redirect_to post_path(@post)
    else
      flash[:error] = @post.errors.full_messages
      redirect_to edit_post_path
    end
  end

  private
  def set_post
    @post = Post.find_by(slug: params[:id])
  end

  def post_params
    params.require(:post).permit!
  end

  def require_creator
    access_denied unless logged_in? && (@post.creator == current_user || current_user.role == 'admin')
  end
end

301/lesson4/lecture8/postit/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title, "New Post" %>
  <%= f.text_field :title %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.label :description, "Post description" %>
  <%= f.text_area :description, size: "5x5"  %>
  <br>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
    <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
  <% end %>
  <br>
  <%= f.submit @post.new_record? ? "Create" : "Update" , class: "btn btn-success" %>
<% end %>

301/lesson4/lecture8/postit/app/views/posts/_post.html.erb
<div class="row">
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: 'true' do %>
        <i class="icon-arrow-up"></i>
      <% end %>
      <br>
    <% end %>
    <span id="post_votes_<%= post.id %>"><%= post.total_votes %></span> Votes
    <% if logged_in? %>
      <br>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: 'true'  do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>
  <div class="span8 well">
    <%= render(post.categories) || "<h6>No category</h6>".html_safe %>
    <h4><%= link_to post.title, post.url %></h4>
    <p><%= post.description %></p>
    <p>
      <span class="quiet">posted by <%= link_to post.creator.username, post_path(post) %></span>
      <small>at <%= display_datetime(post.created_at) %></small>
    </p>
    <span>
      <%= link_to("#{post.comments.size} comments", post_path(post)) %>
    </span>
  </div>
</div>

301/lesson4/lecture8/postit/app/views/posts/edit.html.erb
<%= render '/shared/content_title', title: "Edit #{@post.title}" %>

<%= render "form" %>

301/lesson4/lecture8/postit/app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All posts" %>
<%= render @posts %>

301/lesson4/lecture8/postit/app/views/posts/new.html.erb
<%= render '/shared/content_title', title: "New posts" %>

<%= render "form" %>

301/lesson4/lecture8/postit/app/views/posts/show.html.erb
<% if current_user == @post.creator %>
  <p>[<%= link_to "edit_post", edit_post_path(@post) %>]</p>
<% end %>

<%= render @post.categories %>
<%= render "shared/content_title", title: @post.title %>
<%= @post.description %>
<hr>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= f.label :body, "Comment" %>
    <%= f.text_area :body, size: "5x5" %>
    <br>
    <%= f.submit "Create", class: "btn btn-success" %>
  <% end %>
<% end %>

<%= render(@post.comments) %>

301/lesson4/lecture8/postit/app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $('span#post_votes_<%= @post.id %>').text('<%= @post.total_votes %>')
<% else %>
  <% flash[:error] = 'something wrong' %>
  window.location.reload();
<% end %>